// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace VideoUploader
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for Data.
    /// </summary>
    public static partial class DataExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='patientId'>
            /// </param>
            /// <param name='startDate'>
            /// </param>
            /// <param name='endDate'>
            /// </param>
            /// <param name='skill'>
            /// </param>
            /// <param name='target'>
            /// </param>
            public static IList<PathfinderEvent> Get(this IData operations, string patientId, string startDate, string endDate, string skill, string target)
            {
                return Task.Factory.StartNew(s => ((IData)s).GetAsync(patientId, startDate, endDate, skill, target), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='patientId'>
            /// </param>
            /// <param name='startDate'>
            /// </param>
            /// <param name='endDate'>
            /// </param>
            /// <param name='skill'>
            /// </param>
            /// <param name='target'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<IList<PathfinderEvent>> GetAsync(this IData operations, string patientId, string startDate, string endDate, string skill, string target, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(patientId, startDate, endDate, skill, target, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='pathfinderData'>
            /// </param>
            public static void Post(this IData operations, PathfinderEvent pathfinderData)
            {
                Task.Factory.StartNew(s => ((IData)s).PostAsync(pathfinderData), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='pathfinderData'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task PostAsync(this IData operations, PathfinderEvent pathfinderData, CancellationToken cancellationToken = default(CancellationToken))
            {
                await operations.PostWithHttpMessagesAsync(pathfinderData, null, cancellationToken).ConfigureAwait(false);
            }

    }
}
