// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace VideoUploader
{
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Threading;
    using System.Threading.Tasks;
    using Microsoft.Rest;
    using Models;

    /// <summary>
    /// Extension methods for VideosWithData.
    /// </summary>
    public static partial class VideosWithDataExtensions
    {
            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='patientId'>
            /// </param>
            /// <param name='startTime'>
            /// </param>
            /// <param name='endTime'>
            /// </param>
            public static PathfinderVideoUI Get(this IVideosWithData operations, string patientId, string startTime, string endTime)
            {
                return Task.Factory.StartNew(s => ((IVideosWithData)s).GetAsync(patientId, startTime, endTime), operations, CancellationToken.None, TaskCreationOptions.None, TaskScheduler.Default).Unwrap().GetAwaiter().GetResult();
            }

            /// <param name='operations'>
            /// The operations group for this extension method.
            /// </param>
            /// <param name='patientId'>
            /// </param>
            /// <param name='startTime'>
            /// </param>
            /// <param name='endTime'>
            /// </param>
            /// <param name='cancellationToken'>
            /// The cancellation token.
            /// </param>
            public static async Task<PathfinderVideoUI> GetAsync(this IVideosWithData operations, string patientId, string startTime, string endTime, CancellationToken cancellationToken = default(CancellationToken))
            {
                using (var _result = await operations.GetWithHttpMessagesAsync(patientId, startTime, endTime, null, cancellationToken).ConfigureAwait(false))
                {
                    return _result.Body;
                }
            }

    }
}
