// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace VideoUploader.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PathfinderVideoUI
    {
        /// <summary>
        /// Initializes a new instance of the PathfinderVideoUI class.
        /// </summary>
        public PathfinderVideoUI() { }

        /// <summary>
        /// Initializes a new instance of the PathfinderVideoUI class.
        /// </summary>
        public PathfinderVideoUI(IList<PathfinderEventUI> events = default(IList<PathfinderEventUI>), string uRL = default(string), DateTime? startTime = default(DateTime?), DateTime? endTime = default(DateTime?), string patientId = default(string))
        {
            Events = events;
            URL = uRL;
            StartTime = startTime;
            EndTime = endTime;
            PatientId = patientId;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Events")]
        public IList<PathfinderEventUI> Events { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "URL")]
        public string URL { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "StartTime")]
        public DateTime? StartTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "EndTime")]
        public DateTime? EndTime { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PatientId")]
        public string PatientId { get; set; }

    }
}
