// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace VideoUploader.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PathfinderEventUI
    {
        /// <summary>
        /// Initializes a new instance of the PathfinderEventUI class.
        /// </summary>
        public PathfinderEventUI() { }

        /// <summary>
        /// Initializes a new instance of the PathfinderEventUI class.
        /// </summary>
        public PathfinderEventUI(int? offsetSeconds = default(int?), string skill = default(string), string target = default(string), string result = default(string), string comments = default(string))
        {
            OffsetSeconds = offsetSeconds;
            Skill = skill;
            Target = target;
            Result = result;
            Comments = comments;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "OffsetSeconds")]
        public int? OffsetSeconds { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Skill")]
        public string Skill { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Result")]
        public string Result { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Comments")]
        public string Comments { get; set; }

    }
}
