// Code generated by Microsoft (R) AutoRest Code Generator 0.16.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace VideoUploader.Models
{
    using System;
    using System.Linq;
    using System.Collections.Generic;
    using Newtonsoft.Json;
    using Microsoft.Rest;
    using Microsoft.Rest.Serialization;

    public partial class PathfinderEvent
    {
        /// <summary>
        /// Initializes a new instance of the PathfinderEvent class.
        /// </summary>
        public PathfinderEvent() { }

        /// <summary>
        /// Initializes a new instance of the PathfinderEvent class.
        /// </summary>
        public PathfinderEvent(string patientID = default(string), string timeStamp = default(string), string skill = default(string), string target = default(string), string result = default(string), string comments = default(string))
        {
            PatientID = patientID;
            TimeStamp = timeStamp;
            Skill = skill;
            Target = target;
            Result = result;
            Comments = comments;
        }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "PatientID")]
        public string PatientID { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "TimeStamp")]
        public string TimeStamp { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Skill")]
        public string Skill { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Target")]
        public string Target { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Result")]
        public string Result { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "Comments")]
        public string Comments { get; set; }

    }
}
